const int VIEW_SCENE_BINDING=0;
const int VIEW_ENV_BINDING=1;
const int VIEW_LIGHTS_BINDING=2;
const int VIEW_LIGHT_INDICES_BINDING=3;
const int VIEW_LIGHT_GRID_BINDING=4;
const int VIEW_LIGHT_GRID_SIZE_BINDING=5;
const int VIEW_SHADOW_MAP_BINDING=6;

const int VIEW_ENV_COUNT=32;
